#pragma config(Sensor, in1,    ballSensorTop,  sensorLineFollower)
#pragma config(Sensor, in2,    ballSensorBottom, sensorLineFollower)
#pragma config(Sensor, in7,    gyro,           sensorGyro)
#pragma config(Sensor, in8,    flyEncoder,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  intakepiston,   sensorDigitalOut)
#pragma config(Sensor, dgtl7,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, ballSONAR,      sensorSONAR_raw)
#pragma config(Sensor, I2C_1,  fly1,           sensorNone)
#pragma config(Motor,  port1,           DriveR1,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FlyR1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FlyR2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Intake1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           FlyL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           DriveL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FlyTop,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          DriveR2,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#define flyThreshold 1000
#define ballThreshold 2500
#define integralThreshold 0

int flywheelSpeed = 0;
int motorOutput = 0;
float RPM = 0;
float currTick = 0;
int targetRPM = 0;
float offset = 0;
float battery = 0;
float flywheelTicks = 0;
int FlyTop1 = 0;
int PIDOutput = 0;
int startingRPM = 0;


const unsigned int TrueSpeed[128] =
{
	0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
	0, 21, 21, 21, 22, 22, 22, 23, 24, 24,
	25, 25, 25, 25, 26, 27, 27, 28, 28, 28,
	28, 29, 30, 30, 30, 31, 31, 32, 32, 32,
	33, 33, 34, 34, 35, 35, 35, 36, 36, 37,
	37, 37, 37, 38, 38, 39, 39, 39, 40, 40,
	41, 41, 42, 42, 43, 44, 44, 45, 45, 46,
	46, 47, 47, 48, 48, 49, 50, 50, 51, 52,
	52, 53, 54, 55, 56, 57, 57, 58, 59, 60,
	61, 62, 63, 64, 65, 66, 67, 67, 68, 70,
	71, 72, 72, 73, 74, 76, 77, 78, 79, 79,
	80, 81, 83, 84, 84, 86, 86, 87, 87, 88,
	88, 89, 89, 90, 90,127,127,127
};




#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "Tasks.c"	// file contains tasks

//int flyWheelFilter[5];

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
bool btn7LPressed = false;
bool btn7RPressed = false;

task usercontrol()
{
	// User control code here, inside the loop
	//startTask(motorControl);
	startTask(flyPID);
	startTask(pidControl);
	startTask(RPMLoop);
	startTask(flywheelTick);
	startTask(RPMGRAPH);
	startTask(pyramidControl);
	targetRPM = startingRPM;
	while (true)
	{
		//battery = nAvgBatteryLevel;
		// ~~~~~~~~~~~~~~~~DRIVE~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		if (vexRT[Ch3] > 23 ) //LeftDrive
			motor[DriveL] = TrueSpeed[abs(vexRT[Ch3])];
		else if (vexRT[Ch3] < -23)
			motor[DriveL] = -TrueSpeed[abs(vexRT[Ch3])];
		else
			motor[DriveL] = 0;

		if (vexRT[Ch2] > 23) //RightDrive
			motor[DriveR1] = motor[DriveR2] = TrueSpeed[abs(vexRT[Ch2])];
		else if (vexRT[Ch2] < -23)
			motor[DriveR1] = motor[DriveR2] = -TrueSpeed[abs(vexRT[Ch2])];
		else
			motor[DriveR1] = motor[DriveR2] = 0;



		if(vexRT[Btn8D] == 1)
		{
			targetRPM = 0;
			FlyTop1 = 0;
		}
		else if(vexRT[Btn8R] == 1)
		{
			targetRPM = 1600;
			FlyTop1 = 127;
		}
		else if(vexRT[Btn8L] == 1)
		{
			targetRPM = 2000;
			FlyTop1 = 127;
		}
		else if(vexRT[Btn8U] ==1)
		{
			targetRPM = 2200;
			FlyTop1 = 127;
		}

		if(vexRT[Btn7R] == 1 && btn7RPressed == false)
		{
			targetRPM += 200;
			FlyTop1 = 127;
			if (targetRPM > 2200)
				targetRPM = 2200;
			btn7RPressed = true;
		}
		else if(vexRT[Btn7R] == 0) //&& btn7UPressed == true)
			btn7RPressed = false;

		if(vexRT[Btn7L] == 1 && btn7LPressed == false)
		{
			targetRPM -= 200;
			if (targetRPM < 0){
				targetRPM = 0;
				FlyTop1 = 0;
			}
			btn7LPressed = true;
		}
		else if(vexRT[Btn7L] == 0) //&& btn7DPressed == true)
			btn7LPressed = false;

		if(vexRT[Btn7D] ==1)
		{
			SensorValue[intakepiston] = 1;
		}
		else if(vexRT[Btn7U] ==1)
		{
			SensorValue[intakepiston] = 0;
		}

		if(vexRT[Btn5D] == 1)
		{
			motor[Intake1]=-127;
		}
		else if (vexRT[Btn5U] ==1)
		{
			motor[Intake1]=127;
		}
		else
		{
			motor[Intake1]=0;
		}

		if(vexRT[Btn6D] == 1)
		{
			motor[Intake2]=-127;
		}
		else if(vexRT[Btn6U] ==1)
		{
			motor[Intake2]=127;
		}
		else
		{
			motor[Intake2]=0;
		}
	}
}
